site_name: Quero Bem Estar 

repo_name:
repo_url: https://github.com/UnBArqDsw2025-2-Turma01/2025.2-T01-G6_-QueroBemEstar_Entrega_01

nav:
  - Início: index.md

theme:
  name: material
  language: pt-BR